export const icons = {
    info: './assets/icons/info.svg',
    plusUser: './assets/icons/plus-user.svg',
    plus: './assets/icons/plus.svg',
    photo: './assets/icons/photo.svg',
    clip: './assets/icons/clip.svg',
    fileBlack: '/assets/icons/fileBlack.svg',
    fileWhite: '/assets/icons/fileWhite.svg',
    clocksBlack: '/assets/gifs/clocksBlack.gif',
    clocksWhite: '/assets/gifs/clocksWhite.gif',
    profile: '/assets/icons/profile.svg',
    clocks: '/assets/icons/clocks.svg',
    tick: '/assets/icons/tick.svg',
    tickDouble: '/assets/icons/tick-double.svg',
    settings: '/assets/icons/settings.svg',
    cross: '/assets/icons/cross.svg',
    arrowLeft: '/assets/icons/arrow-left.svg',
    arrowRight: '/assets/icons/arrow-right.svg',
}
